modules:
    - '@fimbul/heimdall'
files:
    - '**/*.{ts,tsx}'
project:
    - packages/instagram-profile
    - packages/instagram-profile/src
    - tools/build-system
    - tools/error-handler
    - tools/proxy-middleware
    - types/typescript-helpers
reportUselessDirectives: error
