name: Node.js CI

on:
    push:
        branches: [$default-branch]
    pull_request:
        branches: [$default-branch]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Install dependencies
              run: yarn
            - name: Build packages
              run: workspaces foreach --include @ladysdoc/instagram-* --exclude root -pv run build
            - name: Collect results
              run: yarn workspaces foreach --include @ladysdoc/instagram-* --exclude root -pv run publish
              env:
                  PUBLIC_PATH: $(pwd)/docs
